{% set version = "11.1.2" %}
{% set pkg = load_setup_py_data() %}

package:
  name: augur
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nextstrain-augur/nextstrain-augur-{{ version }}.tar.gz
  sha256: 2a131514c0aa31cabdb24357a116c8f81e79faff4087caed7b81640195056a9c

build:
  number: 2
  noarch: python
  entry_points:
    - augur = augur.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python {{ pkg.python_requires }}
    - pip

  run:
    - python {{ pkg.python_requires }}

    # Requirements declared in Augur's setup.py
{%
  set pypi_to_conda = {
    "phylo-treetime": "treetime",
  }
%}
{% for req in pkg.install_requires %}
  {% if ' ' in req %}
    {% set name, versions = req.split(maxsplit=1) %}
  {% else %}
    {% set name, versions = req, '' %}
  {% endif %}
    - {{ pypi_to_conda[name] | default(name) }} {{versions.replace(' ', '')}}
{% endfor %}

    # Extras which will typically be desired in a Conda installation of Augur,
    # from PyPI:
    - snakemake >=5.4.0
    - cvxopt >=1.1.9,<2

    # …and non-Python packages.
    - mafft
    - raxml
    - fasttree
    - iqtree
    - vcftools

test:
  imports:
    - augur
  commands:
    - augur --help

about:
  home: https://github.com/nextstrain/augur
  license: AGPL-3.0
  summary: 'Process pathogen genome data for the Nextstrain platform'
  license_family: AGPL
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - huddlej
    - tsibley
