{% set name = "nextalign" %}
{% set version = "0.1.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/nextstrain/nextclade/archive/{{ name }}-{{ version }}.tar.gz
  sha256: f3890c147dabf4cd11ea085e33ef4f00e198990ce25e9cc3d1dda2cf3c2306e2

build:
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - conan
    - coreutils
    - cppcheck
    - make

test:
  commands:
    - nextalign --help

about:
  home: https://github.com/nextstrain/nextclade/tree/master/packages/nextalign_cli
  license: MIT
  license_family: MIT
  summary: "Viral genome clade assignment, mutation calling, and sequence quality checks"
  doc_url: https://github.com/nextstrain/nextclade
  dev_url: https://github.com/nextstrain/nextclade 

extra:
  recipe-maintainers:
    - cjw85
    - huddlej
    - ivan-aksamentov
  skip-lints: []
